name: coffeeshop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.8
  equatable: ^2.0.8
  google_fonts: ^8.1.0
  get_it: ^9.2.1
  dio: ^5.9.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#18120D"
  color_dark: "#18120D"
  image: "assets/images/icon.png"
  image_dark: "assets/images/icon.png"
  android_12:
    color: "#18120D"
    color_dark: "#18120D"
    image: "assets/images/icon.png"
    image_dark: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
